import type { Task } from './types'

export const sampleTasks: Task[] = [
  {
    id: 'sample-1',
    name: 'Research & Planning',
    resource: 'Planning',
    start: '2025-03-01',
    end: '2025-03-07',
    duration: null,
    percentComplete: 100,
    dependencies: [],
    color: '#3b82f6',
  },
  {
    id: 'sample-2',
    name: 'Design Mockups',
    resource: 'Design',
    start: '2025-03-08',
    end: '2025-03-14',
    duration: null,
    percentComplete: 75,
    dependencies: ['sample-1'],
    color: '#8b5cf6',
  },
  {
    id: 'sample-3',
    name: 'Core Development',
    resource: 'Development',
    start: '2025-03-10',
    end: '2025-03-24',
    duration: null,
    percentComplete: 40,
    dependencies: ['sample-1'],
    color: '#10b981',
  },
  {
    id: 'sample-4',
    name: 'Testing & QA',
    resource: 'QA',
    start: '2025-03-25',
    end: '2025-03-31',
    duration: null,
    percentComplete: 0,
    dependencies: ['sample-3'],
    color: '#f59e0b',
  },
  {
    id: 'sample-5',
    name: 'Launch',
    resource: 'Planning',
    start: '2025-04-01',
    end: '2025-04-03',
    duration: null,
    percentComplete: 0,
    dependencies: ['sample-2', 'sample-4'],
    color: '#ef4444',
  },
]
